### ISSUE TITLE
Default Admin login details?

### ISSUE THREAD

**Issue by h1rule** [stormtrooper42/0TS3-CMS#1]
Hey, i was wondering if theres a "Admin" Account and if yes, what is the login?

**Comment by stormtrooper42** [comment]
I work on it, i push new commits when i have 5min for me  ;)

**Comment by h1rule** [comment]
very nice!
also some suggestions:
- limit the maximum slots for each server creation (one guy did 60000 slots)
- verification things, currently its easy to mass register servers :)
- control panel like psychokillers webinterface :)

**Comment by stormtrooper42** [comment]
Hi, 
i'm very busy at the moment, but i promise lot of new features like you want soon ;) 
PS: Sorry for my bad english.

**Comment by mr-thrifty** [comment]
Stormtrooper42, I would like to support this project. Do you have a Paypal or BTC address I could donate to? I would really like to see you add more stuff.

**Comment by stormtrooper42** [comment]
Hey, sorry for the late reply ;) yes i have a BTC address  :   1GQppiiVBnt9PYExfguR4SEdBq4ojV3zfS
Thanks for your interest !

PS : I actually work on a new version of this script ;)
